### ISSUE TITLE
Melhorias

### ISSUE THREAD

**Issue by gentildpinto** [MarioCarlosChita/api-gestao-projecto#1]
Hey @MarioCarlosChita 🤝 

Estive a dar uma olhada neste projeto e reparei em algumas coisas fora do normal num projeto Laravel e eu penso que pode melhorar

As que mais me chamaram a atenção foram:

- O nome do diretório (e o namespace) "model" deveria estar com a primeira letra em maiúscula, tal como os outros diretórios

```php
<?php

namespace App\Model; <- bom

namespace App\model; <- mau
```

- Nomenclatura de classes, funções, variáveis e campos da base de dados
Há inglês misturado com português, por favor não faça isso. Seria melhor se fosse tudo em inglês

- O nome das classes de modelo devem ser criadas sem o sufixo "Model"

```php
<?php

namespace App\model;

use Illuminate\Database\Eloquent\Model;

class TipoUsuarioModel extends Model
{
    protected $table ="tipousuario"; <- as tabelas devem estar no plural e o nome da model no singular
    protected  $fillable =[
        'nome',
        'descricao',
        'id_usuario',
        'id_tipo'
    ];
}
```

- Uso da classe DB para criar consultas na base de dados

A menos que seja realmente necessário o uso dessa classe para consultas o melhor seria usar o ORM Eloquent para fazer este trabalho

```php
private function  TodasVendas(){
     $sql ="select * from  venda";
     return DB::select($sql);
}
```

- E penso que também devias dar uma olhada no tamanho que as funções nos controllers têm, muitas dessas funções fazem muita coisa sem necessidade, deve haver alguma forma de reduzir as muitas responsabilidades que eles têm 👍🏿

**Comment by MarioCarlosChita** [comment]
valeu , mano  obrigado pelas sugestão ,  não   mexo bastante  com o
laravel  , mais  com tudo receber este feedback da tua parte ..
caso tenha mais detalheis pode mandar , obrigado

Em ter., 23 de nov. de 2021 às 09:39, Gentil Pinto ***@***.***>
escreveu:
